services:
  reactpostgresmybackend:
    image: reactpostgresmybackend
    build:
      context: react-postgres-my-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
